apache/curator

curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceDiscoveryImpl.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/TestServiceDiscovery.java

**The issue:** If zookeeper is down when discovery is started, it fails to register when the zookeeper comes up for the first time. However, if the zookeeper is restarted again, it discovery will connect and register the service instance correctly.
**Cause :** This happened because *org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.stateChanged()* considered only *ConnectionState.RECONNECTED* state and not *ConnectionState.CONNECTED*.  This caused the first connection to be ignored, while subsequent connection recoveries worked fine. 
This pull request has fix for the same and a test case for it.

CURATOR-175: If zookeeper is down when discovery is started, it fails to register when the zookeeper comes up for the first time.

---

curator-client/src/main/java/org/apache/curator/utils/ZKPaths.java
curator-client/src/test/java/org/apache/curator/utils/TestZKPaths.java

ZKPaths' makePath currently only accepts one parent and one child nodes.
This changes makePath to have a varargs parameter so it can accept more than one child.

CURATOR-166: Allow ZKPaths to build paths with an arbitrary number of children

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/ChildReaper.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/Reaper.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestChildReaper.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestReaper.java

A fix for the problem described in https://issues.apache.org/jira/browse/CURATOR-187.  The ChildReaper continuously runs even when its Reaper is not the leader, resulting in a pileup of paths to reap in the Reaper's queue. 
This changeset allows the ChildReaper to create the LeaderLatch so that it too can avoid doing any work (i.e. adding paths to the Reaper's queue) if this application is not the leader.

Curator 187

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/ChildReaper.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestChildReaper.java

make sure ChildReaper always moves through all registered nodes. Also, add an optionl check so that large nodes are never queried

make sure ChildReaper always moves through all registered nodes.

---

curator-examples/src/main/java/discovery/InstanceDetails.java
curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/contexts/GenericDiscoveryContext.java
curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/contexts/IntegerDiscoveryContext.java
curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/contexts/StringDiscoveryContext.java
curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/entity/JsonServiceInstanceMarshaller.java
curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/entity/JsonServiceInstancesMarshaller.java
curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/entity/JsonServiceNamesMarshaller.java
curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/rest/DiscoveryContext.java
curator-x-discovery-server/src/test/java/org/apache/curator/x/discovery/server/jetty_jersey/ServiceDetails.java
curator-x-discovery/pom.xml
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceInstance.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/JsonInstanceSerializer.java
curator-x-rpc/src/test/java/org/apache/curator/x/rpc/RpcTests.java
pom.xml

CURATOR-186
One line of executable code changed, here, in
org.apache.curator.x.discovery.server.contexts.GenericDiscoveryContext#unMarshallJson
@Override
public T unMarshallJson(JsonNode node) throws Exception
{
T payload;
ObjectMapper mapper = new ObjectMapper();
//noinspection unchecked
payload = (T)mapper.readValue(mapper.treeAsTokens(node),  // <<<<<<<<<<<<<<<<
payloadType.getRawType());
return payload;
}
Jackson v2 has no method on ObjectMapper supporting readValue(JsonNode, Class).  However, Jackson v1 states the form I used
is a shortcut for that legacy method.
All other changes to the code and poms were simply replacing imports
and maven dependencies.
Jackson 2.3.2 was chosen to be compatible with the version already
being transitively provided through the dependency …

Port Codehaus Jackson to fasterxml Jackson.

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessReadWriteLock.java

Fixing bug described in https://issues.apache.org/jira/browse/CURATOR-211.
In case if `ourIndex` is never assigned in loop it will be equal to `-1` which will result in throwing exception by `StandardLockInternalsDriver.validateOurIndex()`.

CURATOR-211 - Fix readLockPredicate() index validation issue

---

curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestPathChildrenCache.java
curator-test/src/main/java/org/apache/curator/test/DelegatingExecutorService.java
curator-test/src/main/java/org/apache/curator/test/ExecuteCalledWatchingExecutorService.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceCacheBuilder.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceCacheBuilderImpl.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceCacheImpl.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/TestServiceCache.java

Add .executorService variants to ServiceCacheBuilder to allow the caller to specify an ExecutorService or a CloseableExecutorService to be used by the PathChildrenCache embedded in ServiceCacheImpl.
Extracts ExecuteCalledWatchingExecutorService (and DelegatingExecutorService) into the curator-test module for use by TestServiceCache.
Relates to CURATOR-223

[CURATOR-223] Add executorService methods to ServiceCacheBuilder

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentEphemeralNode.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/nodes/TestPersistentEphemeralNode.java

PersistentEphemeralNode can be initialised with certain data, then later updated. If the client reconnects, the replacing ephemeral should write the updated data.

CURATOR-241: Write updated data on reconnect

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/NodeCache.java

CURATOR-167 - Partial fix to clean up Curator managed watch objects whenthe cache closes. A full fix requires the ability to cancel watches in ZK which is not available until ZK 3.5

CURATOR-167 - Partial fix to clean up Curator managed watch objects

---

curator-client/src/main/java/org/apache/curator/connection/ClassicConnectionHandlingPolicy.java
curator-client/src/main/java/org/apache/curator/connection/ConnectionHandlingPolicy.java
curator-client/src/main/java/org/apache/curator/connection/StandardConnectionHandlingPolicy.java
curator-framework/src/main/java/org/apache/curator/framework/imps/ClassicInternalConnectionHandler.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/InternalConnectionHandler.java
curator-framework/src/main/java/org/apache/curator/framework/imps/StandardInternalConnectionHandler.java
curator-framework/src/main/java/org/apache/curator/framework/state/ConnectionStateManager.java

Added an option for session expiration management to be a fraction of the negotiated session timeout. This is meant to account for timing/network differences between the client and server.

Better session expiration management

---

curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java

CURATOR-45 added findAndDeleteProtectedNodeInBackground to handle cases where a protected node can get lost. However, the code wasn't correctly handling namespaces

[CURATOR-264] Duplicate ephemeral nodes with same owner id

---

curator-framework/src/main/java/org/apache/curator/framework/imps/NamespaceFacade.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFramework.java

I just recently upgraded my project to 2.9.0 and noticed that `PathChildrenCache` recipe started failing with
```
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /parent
at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1590) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214) ~[curator-framework-2.9.0.jar:?]
at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203) …
```

CURATOR-270 createContainers does not work correctly with usingNamespace

---

curator-framework/src/main/java/org/apache/curator/framework/EnsureContainers.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestEnsureContainers.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/queue/SimpleDistributedQueue.java

Previous change to create containers broke some old behavior. Old EnsurePath class only created parents once. So, introduce new EnsureContainers class to do similar but for containers. Also, make usage in a protected method so that it can be turned off by users

[CURATOR-274] v2.9.0 broken EnsurePath behavior

---

curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/FindAndDeleteProtectedNodeInBackground.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/queue/DistributedQueue.java

1. Don't queue background operation if the client is closed
2. Moved findAndDeleteProtectedNodeInBackground code into separate operation that is processed through the standard Curator background code. This way, retries are applied (with sleep), etc. In the previous implementation, errors caused the background check to be run immediately and infinitely.

[CURATOR-209] Better handling of background errors

---

curator-client/src/main/java/org/apache/curator/utils/DebugUtils.java
curator-framework/src/main/java/org/apache/curator/framework/imps/NamespaceWatcherMap.java
curator-framework/src/main/java/org/apache/curator/framework/imps/RemoveWatchesBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/WatcherRemovalFacade.java
curator-framework/src/main/java/org/apache/curator/framework/imps/WatcherRemovalManager.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestRemoveWatches.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCache.java
curator-test/src/main/java/org/apache/curator/test/BaseClassForTests.java

Make sure NamespaceWatcherMap is cleared when the corresponding watcher is removed via new APIs. Added tests to ensure this.

[CURATOR-290] Make sure NamespaceWatcherMap is cleared

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentNode.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/nodes/TestPersistentNode.java

Because start() creates the node async, if close is called immediately, it might occur before the node creation. Handle this edge case by having the background response delete (async) the node if the instance has been closed

[CURATOR-297] Handle quick close after start for PersistentNode

---

curator-x-discovery/src/site/confluence/index.confluence

Since NamespaceWatchers cannot be removed in Zookeeper 3.4.x, anyone using the service discovery recipe in Curator 2.x should cache each service provider they create and reuse it for subsequent calls to that service.
@Randgalt let me know if this doc change is along the lines you were thinking.

CURATOR-286: Add note to explain why service providers should be cached/reused

---

curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/rest/DiscoveryResource.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceType.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceDiscoveryImpl.java

Added a new DYNAMIC_SEQUENTIAL  ServiceType for ServiceDiscovery instances, which creates EPHEMERAL_SEQUENTIAL nodes in Zookeeper. Before this patch only EPHEMERAL or PERSISTENT nodes were supported by Service Discovery.  
[Jira issue](https://issues.apache.org/jira/browse/CURATOR-304)

Support EPHEMERAL_SEQUENTIAL nodes for ServiceDiscovery instances

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentNode.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/nodes/TestPersistentNode.java

This is a semi-punt but a reasonable one. The simple solution is for the client to call waitForInitialCreate() before calling setData(). So, now, setData() throws an exception if the initial create has not occurred.

[CURATOR-310] Race in PersistentNode startup

---

curator-framework/src/main/java/org/apache/curator/framework/api/CreateBuilder.java

https://issues.apache.org/jira/browse/CURATOR-317
Now anyone looking at the deprecated annotation will find code that is a drop in replacement.

CURATOR-317: changed a deprecation comment to provide a better equivalent

---

curator-framework/src/main/java/org/apache/curator/framework/imps/Backgrounding.java
curator-framework/src/main/java/org/apache/curator/framework/imps/ClassicInternalConnectionHandler.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorMultiTransactionImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/DeleteBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/ExistsBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/FindAndDeleteProtectedNodeInBackground.java
curator-framework/src/main/java/org/apache/curator/framework/imps/GetACLBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/GetChildrenBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/GetConfigBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/GetDataBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/OperationAndData.java
curator-framework/src/main/java/org/apache/curator/framework/imps/ReconfigBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/RemoveWatchesBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/SetACLBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/SetDataBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/SyncBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/Watching.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestWatcherRemovalManager.java

If there's an exeption, retries exceeded, etc., the watcher was still being stored in WatcherRemovalManager thus causing it to be incorrectly removed. This fix removes the watch from the WatcherRemovalmanager on exceptions, retries exceeded, etc.

[CURATOR-299] WatcherRemovalManager must be updated when there's an exception, retry, etc.

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessSemaphoreV2.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestInterProcessSemaphore.java

Only add successfully acquired leases to the builder passed to internalAcquire1Lease. Close leases on other return paths.
This ensures that acquire does not return more leases than requested, as it is expected by the convenience methods for acquiring a single lease.

[CURATOR-315] Reconnect during InterProcessSemaphoreV2.acquire can lead to orphaned node

---

curator-framework/src/main/java/org/apache/curator/framework/imps/ExistsBuilderImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java

exists() with createParentContainersIfNeeded was ignoring too many KeeperExceptions and thus hiding connection problems. Should only ignore node exists/not-exists

[CURATOR-326] exists() with createParentContainersIfNeeded was ignoring too many KeeperExceptions

---

curator-framework/src/main/java/org/apache/curator/framework/EnsureContainers.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/queue/SimpleDistributedQueue.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/queue/TestSimpleDistributedQueue.java

Parent container deletions could cause a hang as the watcher would never fire. If parent containers get deleted now, reset and recreate them

[CURATOR-308] Parent container deletions could cause a hang

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedValue.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/shared/TestSharedCount.java

Fixed SharedValue class to correctly update its value on start() call to value stored in Zookeeper node if node version is zero.

CURATOR-329 - SharedValue does not update to current value if zookeeper node version is 0

---

curator-framework/pom.xml
curator-framework/src/main/java/org/apache/curator/framework/imps/Backgrounding.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java
curator-framework/src/main/java/org/apache/curator/framework/imps/ExistsBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/GetChildrenBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/GetConfigBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/GetDataBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/OperationAndData.java
curator-framework/src/main/java/org/apache/curator/framework/imps/RemoveWatchesBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/Watching.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestCleanState.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestWatcherRemovalManager.java
curator-recipes/pom.xml
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/shared/TestSharedCount.java
pom.xml

Reworked WatcherRemovalManager. It now stores watchers only on successful operations. This is more like how ZK does it.
Also, exists watcher must be stored when there is a NoNode result.

[CURATOR-332] Internal watcher tracking for new WatcherRemoveCuratorFramework feature is not correct

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCache.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestTreeCache.java

It will allow to add a custom error handlers for the treeCache.

[CURATOR-331] Make unhandledErrorListenable as public

---

curator-framework/src/main/java/org/apache/curator/framework/imps/GzipCompressionProvider.java

explicitly close GZIP input/output streams in GzipCompressionProvider

CURATOR-354: native memory leak in GzipCompressionProvider

---

curator-client/src/main/java/org/apache/curator/ConnectionState.java

The default session id inside ZooKeeper is 0, we should keep consistent with it in tracker.

[CURATOR-349] Trace the session id even when it is disconnected

---

curator-test/src/main/java/org/apache/curator/test/InstanceSpec.java
curator-test/src/main/java/org/apache/curator/test/QuorumConfigBuilder.java

Currently, when we create a TestingCluster, all the TestingServers will be bound to the local interface (127.0.0.1). This becomes a constraint if we want to run a TestingCluster which can be used for testing over a network (say LAN).
To provide more flexibility over network interfaces, I have added the concept of **hostname** into the **InstanceSpec** class in this PR.

[CURATOR-360] Allow TestingCluster to listen on other network interfaces

---

curator-framework/src/main/java/org/apache/curator/framework/imps/NamespaceImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestNamespaceFacade.java

In the test, I'm casting `CuratorFramework` to `CuratorFrameworkImpl` to get access to `unfixForNamespace()`. It was the most direct way to write the test, but I'm open to suggestions for cleaner code.

[CURATOR-361] Prevent removal of leading slash from path when empty namespace used

---

curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java

Logging the configuration data only after it has been parsed into a `Properties` object. This allows logging readable text instead of an array of bytes.
Also guarded the log statement with a test on the log level, as `Properties.toString()` is a costly operation.

[CURATOR-369] Improve log for new configuration events

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessSemaphoreMutex.java

Set this.lease to null before lease.close.

[CURATOR-376] InterProcessSemaphoreMutex is not thread safe

---

curator-client/pom.xml
curator-recipes/pom.xml
curator-test/pom.xml
curator-x-discovery/pom.xml
pom.xml

Shaded Guava into Curator Client (and Curator Test) so that it's no longer an issue for users. This should have been done a long time ago. Unfortunately, `com.google.common.base.Function`, `com.google.common.base.Predicate` and `com.google.common.reflect.TypeToken` are in Curator's public API so those 3 classes are NOT shaded. However, this won't be a problem because there's no reason to think that Guava will change or remove these basic interfaces.
NOTE: I've tested this by creating a temp project that uses Guava 21.0-rc2. When used with Curator 2.11.1 I get a `NoSuchMethodError`. When used with this new shaded version of Curator there are no errors.

[CURATOR-200] Shade Guava into Curator

---

curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceInstance.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceInstanceBuilder.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/EnabledInstanceFilter.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceProviderImpl.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/TestJsonInstanceSerializer.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/details/TestServiceProvider.java

Service providers will omit any instance that is marked 'enabled: false'.
The low level API provided by ServiceDiscovery (e.g. queryForInstance,
queryForInstances) will continue to return all instances, including
those that are marked 'enabled: false'.
This change allows instances to be temporarily removed from service
discovery via an update to the instance node data.

[CURATOR-275] Allow service instances to be disabled temporarily

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestPathChildrenCacheInCluster.java

Using only Stat version to note node change (for UPDATE event) is not enough. In a split brain if a node delete plus a recreate is missed, the Stat version can appear to be the same. So, when data is available in the cache, compare the data not the stat version

[CURATOR-391] Cannot use only Stat version to determine node change

---

pom.xml

Currently, the `mvn compile` failed on CURATOR-3.0 branch, it turns out clirr maven plugin has bug and can fail on Java 8, the latest 2.8 version fixed those bug, and compiled without error.
Error details:
-------------------
[ERROR] Failed to execute goal org.codehaus.mojo:clirr-maven-plugin:2.6.1:check (default) on project curator-x-async: Execution default of goal org.codehaus.mojo:clirr-maven-plugin:2.6.1:check failed: Invalid byte tag in constant pool: 15

[CURATOR-400] upgrade clirr to fix the check error on java 8

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessMutex.java

See https://issues.apache.org/jira/browse/CURATOR-401

CURATOR-401: Make InterProcessMutex.isOwnedByCurrentThread public

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentNode.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentNodeListener.java

This provides ability to hook into events from PersistentNode when a
node gets created.  PersistentNode would then notify any registered listeners that the 
node was created, along with the path created (useful when protection is used).

[CURATOR-386] Allow listener to be passed in to PersistentNode

---

curator-x-async/src/main/java/org/apache/curator/x/async/api/AsyncTransactionCreateBuilder.java
curator-x-async/src/main/java/org/apache/curator/x/async/details/AsyncTransactionOpImpl.java

intermediate AsyncTransactionCreateBuilder DSL methods should return AsyncPathAndBytesable not AsyncPathable.
The good news here is the 99.9% of old clients will still work as this is an intermediate API call only. e.g.
`client.transactionOp().create().compressed().forPath()` still works. It merely now gains the ability to set the byte array (as it should).

[CURATOR-404] AsyncTransactionCreateBuilder has API mistake

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedCount.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedValue.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/shared/TestSharedCount.java

This PR introduces to refresh data when client's state becomes ConnectionState.RECONNECTED.

[CURATOR-311] SharedValue could hold stall data after reconnecting

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedCount.java

`removeListener` only removed the listener from the SharedCount's `listeners` member, which had no effect.
This fix retrieves the `SharedValueListener` created for wrapping the `SharedCountListener` and removes it from the SharedValue's listeners.

SharedCount: fix removeListener

---

curator-x-async/src/main/java/org/apache/curator/x/async/details/AsyncTransactionOpImpl.java
curator-x-async/src/test/java/org/apache/curator/x/async/CompletableBaseClassForTests.java
curator-x-async/src/test/java/org/apache/curator/x/async/TestBasicOperations.java

Fixed create mode for AsyncCuratorFramework.transactionOp().create(). It was being ignored. Added a test as well.

[CURATOR-423] Fixed create mode for AsyncCuratorFramework.transactionOp().create().

---

curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java

The client address in Zookeeper can be a wildcard (0.0.0.0), and if this is used by Curator, it will attempt to create a new connection to 0.0.0.0 instead of the correct server address. It is also possible that no client address or port is set, which should be counted as invalid by Curator, since the appropriate information isn't contained in the data sent.

[CURATOR-392] Fixing connection string construction for wildcard client addresses

---

curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestCreateReturningStat.java

-The stat object was not being populated if the create failed due to the node already existing.

CURATOR-431 - Fixed stat population during create

---

curator-client/src/main/java/org/apache/curator/utils/ZKPaths.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java

use `curatorFramework.delete().deletingChildrenIfNeeded().forPath(path)`, this sync api doesn't ignore the NoNodeException, causes the rest of children nodes will not be deleted perhaps.  
`zookeeper.getChildren(path, null)` maybe throw NoNodeException, if the path doesn't exist.

[CURATOR-430] deletingChildrenIfNeeded maybe cannot delete children completely when multi-client delete concurrently

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/LockInternals.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/TestLeaderLatch.java

getSortedChildren() should ignore NoNode exceptions and just treat it as if there are no children. This works around issues with container nodes, parents not yet created, etc.

[CURATOR-436] getSortedChildren() should ignore NoNode exceptions

---

curator-framework/src/main/java/org/apache/curator/framework/listen/ListenerContainer.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessMutex.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/queue/QueueBuilder.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedCount.java

This pull request addresses CURATOR-438 which replaces all occurrences of the deprecated MoreExecutors.sameTheadExecutor() with MoreExecutors.directExecutor(). 
This has been an issue before a couple times, but some lingering calls remained so I searched them down and fixed them.

CURATOR-438 Replace Deprecated Methods

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestPathChildrenCache.java

PathChildrenCache stops working if container node is auto-removed and later recreated - test and a fix

[CURATOR-388] PathChildrenCache stops working if container node is auto-removed

---

curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/OperationAndData.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java

To avoid massive spinning, background operations are paused for 1 second when there is no connection. However, this can hurt performance terribly if background operations are queued, for example, prior to initial connection. This changes the behavior so that the sleeps are cleared when the connection is re-established. A separate queue of "forced sleep" operations are kept while the connection is down. This queue then gets its sleep cleared when the connection is re-established.
Reviewers - please verify this logic. I think I have it right. I'm only concerned that I might be leaking operations into `forcedSleepOperations` that never get cleared.

[CURATOR-443] CuratorFrameworkImpl may sleep in foreground even if inBackground is called

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCache.java

Jira https://issues.apache.org/jira/browse/CURATOR-374 reduced per-node memory usage in `TreeCache`. It can be improved further via removal of the `nodeState` field - its `LIVE` state corresponds exactly to the adjacent `childData` field being non-null, and a sentinel `ChildData` value can be used for the `DEAD` state. This simplification also reduces the room for bugs and state inconsistencies.
Other improvements included:
* More robust cache update logic (in get-children and get-data event callbacks)
* ~~A further simplification to have `TreeNode` extend `AtomicReference`, which obviates the need for an explicit `childData` field~~
* ~~Avoid overhead of incrementing/decrementing the `outstandingOps` atomic integer post-initialization~~
See corresponding JIRA: …

[CURATOR-447] TreeCache: Improve memory usage and concurrent update logic

---

src/site/confluence/errors.confluence
src/site/confluence/getting-started.confluence
src/site/confluence/logging.confluence

with protocol update for apache.org, slf4j.org and wikipedia.org.

[CURATOR-450] Fix dead link in 'Getting Started' documentation

---

curator-client/src/main/java/org/apache/curator/ConnectionState.java
curator-client/src/main/java/org/apache/curator/CuratorZookeeperClient.java
curator-client/src/main/java/org/apache/curator/HandleHolder.java
curator-framework/src/main/java/org/apache/curator/framework/CuratorFrameworkFactory.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/test/java/org/apache/curator/framework/state/TestConnectionStateManager.java
pom.xml

Add a new close(int timeout) API in order to leverage ZooKeeper#close(timeout) API introduced in ZK 4.5.4-BETA.
Summary of changes:
- bump ZK to 4.5.4-BETA
- add the implementation of the feature
- add a missing license header

CURATOR-408 Handle graceful close of ZookKeeper client waiting for all resources to be released

---

curator-client/src/main/java/org/apache/curator/CuratorZookeeperClient.java

Before, regardless of the value set in `connectionTimeoutMs` the
CuratorZookeeperClient#internalBlockUntilConnectedOrTimedOut method did
the initial wait with value of 1 second, which made settings lower than
this value ineffective. This proved problematic in several use cases
where such minimum for timeout is prohibitively large.

Support client timeouts < 1000ms

---

curator-client/src/main/java/org/apache/curator/HandleHolder.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestTtlNodes.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/nodes/TestPersistentTtlNode.java

Fixed 2 problems: 1) internalClose can be called from a ZooKeeper background thread (as part of a Watcher callback). Calling ZooKeeper.close with a waitForShutdownTimeoutMs in this case will cause a deadlock as no other events can be processed until the current thread exits. 2) All TTL tests must set the system property "zookeeper.extendedTypesEnabled"
Note: all tests pass for me now

CURATOR-472 - fix deadlocks during tests as well as TTL test issues

---

curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/ModeledFrameworkImpl.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestModeledFramework.java

using the passed in version in ModeledFrameworkImpl.delete

[CURATOR-480] fixed ModeledFrameworkImpl.delete version handling

---

curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java

[CURATOR-493] Fix test case with testDeleteChildrenConcurrently

---

curator-framework/src/main/java/org/apache/curator/framework/state/ConnectionStateManager.java

Once the session expiration is injected, reset startOfSuspendedEpoch so that we don't do this copious times while things are being reset.

[CURATOR-405] reset startOfSuspendedEpoch when session expiration is injected

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelector.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/TestLeaderSelector.java

Adds a test to what #279 had along with a slightly more complete fix. The finally clause of doWork() releases the mutex. In an interrupted situation this would always fail causing the failed delete manager to handle the work resulting in slightly slower deletions and spurious log messaged. This fixes this by clearing the thread interrupted state prior to releasing the mutex and then resetting afterwards if needed.

[CURATOR-468] LeaderSelector interruption causing spurious log messages, etc.

---

curator-framework/src/main/java/org/apache/curator/framework/imps/GzipCompressionProvider.java
curator-framework/src/test/java/org/apache/curator/framework/imps/GzipCompressionProviderTest.java

This PR addresses https://issues.apache.org/jira/browse/CURATOR-487 by recycling Deflaters and Inflaters in static concurrent pools. Since Deflaters and Inflaters are acquired and returned to the pools in try-finally blocks that are free of blocking calls themselves, it's not expected that the number of objects in the pools could exceed the number of hardware threads on the machine much. Therefore it's accepted to have simple pools of strongly-referenced objects.
Just an interesting cross project reference, similar task in Jetty: https://github.com/eclipse/jetty.project/issues/300

CURATOR-487 Make GzipCompressionProvider to recycle Deflaters and Inflaters in pools

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCache.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestTreeCache.java

In our use case, we use `TreeCache` to get Zk Data periodically. We start `TreeCache` read data and close it. In this use case, The `ZkWatchManager` of `ZooKeeper` class keeps growing for every TreeCache operation because new `TreeNode` objects are created and added there leading to a memory leak. Also since we do not want the Watcher to periodically watch, this creates  unnecessary background operations.
In this PR, Made the createZkWatches configurable in the Builder, so that use cases like ours can set it to false. The default is true, retaining the current behaviour.
Fixes the jira issue https://issues.apache.org/jira/browse/CURATOR-477

[CURATOR-477] added support for turning off zk watches

---

curator-client/src/main/java/org/apache/curator/utils/ZKPaths.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/queue/DistributedDelayQueue.java

Currently ZKPaths.makePath() methods call substring() unnecessarily. I've seen those methods responsible for 15% of total heap allocation in some application.

CURATOR-494 Make ZKPaths.makePath() methods to allocate less garbage

---

curator-x-async/src/main/java/org/apache/curator/x/async/modeled/ZPath.java
curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/CachedModeledFrameworkImpl.java
curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/ZPathImpl.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestCachedModeledFramework.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestZPath.java

CachedModeledFrameworkImpl.children() and CachedModeledFrameworkImpl.childrenAsZNodes() were not implemented correctly but neither was the previous commit for this. This is the correct fix. Previous commit was returning full tree, should be 1 level only

[CURATOR-479] - CachedModeledFrameworkImpl.children() and CachedModeledFrameworkImpl.childrenAsZNodes() were not implemented correctly

---

curator-framework/src/main/java/org/apache/curator/framework/schema/SchemaViolation.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/queue/TestDistributedQueue.java
curator-x-discovery-server/pom.xml
pom.xml

The main motivation for this update is updating Guava from 20.0 to 27.0.1-jre. Between these versions, the implementation of `Maps.newConcurrentMap()` (this method is used in many places in Curator code) was changed and now it returns `ConcurrentHashMap` instead of Guava's own implementation, that was less efficient.
This PR also updates Jackson version, as well as #280, from 2.7 to 2.9. Answering questions raised in the comments to that PR: I believe upgrading Jackson from 2.7 to 2.9 is safe. The compatibility standards in Jackson are much higher than in an average Java project. Most incompatibilities in [2.8](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8#changes-compatibility) and [2.9](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9#changes-compatibility) …

[CURATOR-503] Update dependencies in January 2019

---

pom.xml

changed phase of maven-license-plugin to validate in order to avoid compilation and testing of invalid code (fail as early as possible)

changed phase of maven-license-plugin to validate 

---

curator-client/pom.xml
curator-framework/pom.xml
curator-recipes/pom.xml
curator-x-discovery-server/pom.xml
curator-x-discovery/pom.xml

Issue: https://issues.apache.org/jira/browse/CURATOR-429
Curator 4.0 supports ZooKeeper 3.4.x (https://curator.apache.org/zk-compatibility.html)
This change allows this dependency also in OSGi. (where it required 3.5)

[CURATOR-429] Make Curator 4.x compatible with Zookeeper 3.4.x in OSGi too

---

src/site/confluence/index.confluence

The Stack Overflow "curator" tag got merged with "apache-curator" and both Stack Overflow links now redirect to the same page. The obsolete link doesn't add anything useful.

[CURATOR-539] Remove link to obsolete Stack Overflow tag

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java

make getOurPath() public for reference purposes

[CURATOR-537] make getOurPath() public

---

curator-test/src/main/java/org/apache/curator/test/BaseClassForTests.java

The retry code in BaseClassForTests was hopelessly broken - I don't know for how long. Reworked it so that it does the right thing now (hopefully). Storing the retry count as an attribute wasn't working. The new method stores it as a field in the test class and makes sure that it's always correct. It should only ever be true when actually retrying and, given that TestNG always calls the retry method, it can be reset after a retry fails.

[CURATOR-541] Fix retry code in BaseClassForTests

---

curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestLockACLs.java

ZOOKEEPER-1392 broke TestLockACLs. In order to read ACLS you now need READ perm. TestLockACLs.testLockACLs() needs to be updated to reflect this.

CURATOR-543 - ZOOKEEPER-1392 broke TestLockACLs

---

curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/ModeledCacheImpl.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestCachedModeledFramework.java

Bad copy/paste bug. ModeledCacheImpl.currentData() was removing from entries instead of calling get()

[CURATOR-546] - ModeledCacheImpl.currentData() was removing from entries instead of calling get()

---

curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceCacheBuilder.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceProviderBuilder.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceCacheBuilderImpl.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceCacheImpl.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceProviderBuilderImpl.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceProviderImpl.java

- ServiceCacheImpl should allow the self-created executor service to be closed
- Allow an optional executor service for ServiceProvider
fix #CURATOR-557

[CURATOR-557] ServiceCacheImpl does not close ExecutorService

---

curator-client/src/main/java/org/apache/curator/ConnectionState.java
curator-client/src/main/java/org/apache/curator/HandleHolder.java
curator-client/src/main/java/org/apache/curator/Helper.java

Commit 26364c6186fc7c09a9462557b1ca791e9aa70006 (Sat Sep 26 13:13:02 2015) changed HandleHolder.getNewConnectionString() was changed to return the new connection string instead of just a boolean. I believe the value returned should have been ensembleProvider.getConnectionString() not helper.getConnectionString(). TBH I no longer remember the genesis of this change but I can't make the current implementation make sense.
Additionally, a change was made to optionally call zooKeeper.updateServerList(). When this path is taken the handle holder's connection needs to be updated as well or we'll get an infinite loop of changes. The path that runs when ensembleProvider.updateServerListEnabled() is false ends up setting handle holder's connection to ensembleProvider.getConnectionString().
I'm …

[CURATOR-551] Fix Handle Holder new connection string

---

curator-test/src/main/java/org/apache/curator/test/InstanceSpec.java
curator-test/src/main/java/org/apache/curator/test/QuorumConfigBuilder.java
curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperMain.java
curator-test/src/main/java/org/apache/curator/test/compatibility/Timing2.java

a) make sure setReuseAddress is set for server when getting a random port
b) always set "tickTime" and "minSessionTimeout" to make our tests run a bit faster
c) fixed incorrect exception message in blockUntilStarted()

[CURATOR-560] set tickTime and minSessionTimeout

---

curator-client/src/main/java/org/apache/curator/CuratorZookeeperClient.java
curator-client/src/main/java/org/apache/curator/RetryLoop.java
curator-client/src/main/java/org/apache/curator/RetryLoopImpl.java
curator-client/src/main/java/org/apache/curator/connection/StandardConnectionHandlingPolicy.java
curator-client/src/main/java/org/apache/curator/connection/ThreadLocalRetryLoop.java
curator-client/src/test/java/org/apache/curator/TestEnsurePath.java
curator-recipes/src/test/java/org/apache/curator/connection/TestThreadLocalRetryLoop.java

The retry loop mechanism ended up getting nested multiple times causing exponential calls to the retry policy and violating a given policy's limits. Use a thread local to mitigate this so that a retry loop is reused for nested API calls, etc.

[CURATOR-559] Fix nested retry loops

---

curator-client/src/main/java/org/apache/curator/utils/Compatibility.java
curator-client/src/test/java/org/apache/curator/TestIs36.java
curator-framework/src/main/java/org/apache/curator/framework/CuratorFramework.java
curator-framework/src/main/java/org/apache/curator/framework/api/AddWatchBuilder.java
curator-framework/src/main/java/org/apache/curator/framework/api/AddWatchBuilder2.java
curator-framework/src/main/java/org/apache/curator/framework/api/Watchable.java
curator-framework/src/main/java/org/apache/curator/framework/api/WatchableBase.java
curator-framework/src/main/java/org/apache/curator/framework/api/WatchesBuilder.java
curator-framework/src/main/java/org/apache/curator/framework/imps/AddWatchBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/WatchesBuilderImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestWatchesBuilder.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestWithCluster.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/TestLeaderSelectorEdges.java
curator-test-zk35/src/test/java/org/apache/curator/framework/TestCompatibility.java
curator-x-async/src/main/java/org/apache/curator/x/async/api/AsyncCuratorFrameworkDsl.java
curator-x-async/src/main/java/org/apache/curator/x/async/api/AsyncWatchBuilder.java
curator-x-async/src/main/java/org/apache/curator/x/async/api/AsyncWatchBuilder2.java
curator-x-async/src/main/java/org/apache/curator/x/async/details/AsyncCuratorFrameworkImpl.java
curator-x-async/src/main/java/org/apache/curator/x/async/details/AsyncWatchBuilderImpl.java
curator-x-async/src/test/java/org/apache/curator/framework/imps/TestAddWatch.java

See: https://github.com/apache/zookeeper/pull/1106
Support persistent watchers in ZK 3.6+ while maintaining background compatibility with previous versions of ZK. Adds Curator Framework DSL calls to ZooKeeper's `addWatch()` method. Subsequent PRs will add recipes. Both the older Framework and the async Framework now have methods to add persistent watchers.

[CURATOR-549] Support ZooKeeper 3.6.0 Persistent Recursive Watchers

---

curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReadOnly.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestWithCluster.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestPathChildrenCacheInCluster.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/TestLeaderLatch.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/TestLeaderLatchCluster.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/TestLeaderSelectorCluster.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestInterProcessSemaphoreCluster.java
curator-test/src/main/java/org/apache/curator/test/BaseClassForTests.java

Like was done for TestingServer, catch startup issues for TestingCluster and then re-recreate and re-start the cluster one time. Hopefully this will make the tests more stable.

[CURATOR-564] catch startup issues for TestingCluster

---

curator-examples/src/main/java/cache/CuratorCacheExample.java
curator-examples/src/site/confluence/index.confluence
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCache.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheAccessor.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheBuilder.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheBuilderImpl.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheImpl.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheListener.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheListenerBuilder.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheListenerBuilderImpl.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheStorage.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/NodeCache.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/NodeCacheListenerWrapper.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/OutstandingOps.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCache.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCacheListenerWrapper.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/StandardCuratorCacheStorage.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCache.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCacheListenerWrapper.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/watch/PersistentWatcher.java
curator-recipes/src/site/confluence/curator-cache.confluence
curator-recipes/src/site/confluence/index.confluence
curator-recipes/src/site/confluence/persistent-watcher.confluence
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestCuratorCache.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestCuratorCacheConsistency.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestCuratorCacheEdges.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestCuratorCacheEventOrdering.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestCuratorCacheWrappers.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestWrappedNodeCache.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/watch/TestPersistentWatcher.java

See: https://github.com/apache/zookeeper/pull/1106
This PR adds several recipes that use the new ZOOKEEPER-1416 Persistent Recursive watches from ZooKeeper 3.6.0.
A wrapper recipe that keeps a persistent (single or recursive) watch set and active through disconnections, etc.
See: [PersistentWatcher.java](https://github.com/apache/curator/blob/CURATOR-549-zk36-persistent-watcher-recipes/curator-recipes/src/main/java/org/apache/curator/framework/recipes/watch/PersistentWatcher.java)
Completely re-written cache recipe that will replace `TreeCache`, `NodeCache` and `PathChildrenCache`. With the benefit of persistent recursive watchers and the new PersistentWatcher recipe, the implementation is far simpler, will use significantly less resources and network calls, be easier to support and …

[CURATOR-549] Recipes based on Persistent Recursive Watchers

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCache.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCacheEvent.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCacheIterator.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/BaseTestTreeCache.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestTreeCacheIteratorAndSize.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestTreeCacheRandomTree.java

The next phase of this issue will implement a bridge cache that bridges TreeCache for pre 3.6 SK and CuratorCache for ZK 3.6+. That bridge will need this TreeCache iterator.

[CURATOR-549] - TreeCacheIterator needed by upcoming CuratorCacheBridge

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CompatibleCuratorCacheBridge.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCache.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheBridge.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheBridgeBuilder.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheBridgeBuilderImpl.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheImpl.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheStorage.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCacheListenerWrapper.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/GroupMember.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestCuratorCacheBridge.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/nodes/TestGroupMember.java
curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/ModeledCacheImpl.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestCachedModeledFramework.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceCache.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceCacheBuilder.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceProviderBuilder.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceCacheBuilderImpl.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceCacheImpl.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceDiscoveryImpl.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceProviderBuilderImpl.java
curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceProviderImpl.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/ServiceCacheLeakTester.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/TestServiceCache.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/details/TestServiceCacheRace.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/details/TestServiceDiscovery.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/details/TestServiceDiscoveryBuilder.java
curator-x-discovery/src/test/java/org/apache/curator/x/discovery/details/TestServiceProvider.java
src/site/confluence/breaking-changes.confluence

Note: this PR is based off #335 
See: https://github.com/apache/zookeeper/pull/1106
It would be nice if Curator's internal use of caches got the benefit of CuratorCache/Persistent Watches. This PR creates a simple bridge that, when using ZK 3.6.0 creates a `CuratorCache`, and for earlier versions creates a `TreeCache`. The `curator-test-zk35` module ensures that both code paths are tested.
Important files:
- [CompatibleCuratorCacheBridge.java](https://github.com/apache/curator/blob/d16271a644d62f8bdd9470dcb1cc30fafdc3f247/curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CompatibleCuratorCacheBridge.java) - this is the wrapper around TreeCache
- [CuratorCacheBridgeBuilderImpl.java](https://github.com/apache/curator/blob/d16271a644d62f8bdd9470dcb1cc30fafdc3f247/curato …

[CURATOR-549] Bridge facade for ModeledCache and ServiceCache, etc.

---

curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/state/ConnectionStateManager.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java

There is a race whereby the ZooKeeper connection can be healed before Curator is finished processing the new connection state. When this happens the Curator instance becomes a Zombie stuck in the LOST state. This fix is a "hack". ConnectionStateManager will notice that the connection state is LOST but that the Curator instance reports that it is connected. When this happens, it is logged and the connection is reset.

[CURATOR-525] Fix for Zombie LOST Curator

---

curator-recipes/src/test/java/org/apache/curator/connection/TestThreadLocalRetryLoop.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestInterProcessMutexBase.java

Calls to `TestCleanState.closeAndTestClean()` in the code have realized their purpose and can likely be removed. They add flakiness to our tests. I'll leave this ticket open and slowly remove calls from the code as Travis complains about them.

[CURATOR-567] remove test clean state where flaky

---

pom.xml

Would like to revisit the following issue.
https://issues.apache.org/jira/browse/CURATOR-464
The current approach would be preventing shaded artifacts from replacing original artifacts. Instead, shaded artifacts are now also attached with classifier uber, next to original artifacts, so clients could integrate either based on their need.
This approach is my preference while it'll be a little expensive in adoption, as new classifier must be added during upgrade. If this really bothers, here are 2 alternatives we may go:
1. **Removing the reloaction in shading.** Packages like `org.apache.curator.shaded.com.google` could be found nowhere but in curator-client, which doesn't export these relocated packages in its manifest. Without relocation, these packages could be fulfilled by some other …

[CURATOR-464] attach orignal artifacts with classifier original

---

pom.xml
src/site/confluence/index.confluence

Follow-up changes of https://github.com/apache/curator/pull/355, to address the remaining concerns raised inside.
_Why do we need ant and build helper plugins. Can't install-file from the install plugin be used?_
There's some slight difference between. The helper plugin attaches a new artifact to the project, and this info could be consumed by any execution of plugins afterwards. For instance, the install plugin is not explicitly told to install another file, and yet it does so by learning there's more than 1 artifact in this project. If nobody else consumes that info, the goal `attach-artifact` and `install-file` could work interchangeably.
I tried to engage `install-file`, on the other hand, and it didn't work well. The primary problem would be it doesn't support conditional install, so …

[CURATOR-464] update classifier and document accordingly

---

curator-recipes/src/test/java/org/apache/curator/connection/TestThreadLocalRetryLoop.java

more attempts to keep tests from failing. Make sure count is zeroed after server is stopped.

[CURATOR-559] - more attempts to keep tests from failing.

---

curator-framework/src/main/java/org/apache/curator/framework/CuratorFrameworkFactory.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java

CURATOR-568
Adding ensembleTracker(boolean) and withEnsembleTracker() methods to
CuratorFrameworkFactory.builder() that allows enabling/disabling
ensemble tracking

CURATOR-568-option-CF-skip-ensemble-tracking

---

pom.xml
src/site/confluence/index.confluence
src/site/confluence/releases.confluence.vm
src/site/site.xml

Add a dedicated downloads page to the website.
The new version of the website can be seen here: http://curator.apache.org/staging/
I tried using the Build Helper plugin to get the current release version but it picked an old version on my machine and left me not trusting it. So, we now have a property specifically for the download page in the root POM: `currentStableVersion`. Once this new website is released I'll update the instructions on the wiki page for building the website.

CURATOR-577 - Add a dedicated downloads page to the website

---

curator-client/pom.xml
curator-framework/pom.xml
curator-recipes/pom.xml
curator-x-discovery-server/pom.xml
curator-x-discovery/pom.xml

According to https://access.redhat.com/documentation/en-us/red_hat_fuse/7.2/html/deploying_into_apache_karaf/buildbundle this is the correct pattern for wildcard in export package config. Also it fixes the problem that IDEA complains with `The package 'org.apache.curator.framework.api' is not exported by the bundle dependencies`
cc @Randgalt @eolivelli @cammckenzie

CURATOR-581. fix OSGi export pattern

---

curator-test/src/main/java/org/apache/curator/test/TestingServer.java
curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperMain.java
curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperServer.java
curator-test/src/test/java/org/apache/curator/test/TestTestingServer.java

https://issues.apache.org/jira/browse/CURATOR-594

CURATOR-594: TestingZooKeeperMain isn't setting tickTime, if configured

---

curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java
curator-test/src/main/java/org/apache/curator/test/TestingQuorumPeerMain.java
pom.xml

It looks like upgrading to ZK 3.6.3 is not that easy as for 3.6.2

CURATOR-588  Upgrade ZooKeeper to 3.6.3

---

curator-client/pom.xml
curator-client/src/test/java/org/apache/curator/BasicTests.java
curator-client/src/test/java/org/apache/curator/utils/TestCloseableExecutorService.java
curator-framework/pom.xml
curator-framework/src/test/java/org/apache/curator/framework/imps/TestCleanState.java
pom.xml

- Use Awaitility to avoid busy waiting.
- Refactor some code to Java8

Use Awaitility to instead of Thread sheep method.

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessReadWriteLock.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestInterProcessReadWriteLock.java

Another and simpler alternative would be exposing it directly in `InterProcessReadWriteLock`:
```
protected String getLockPath()
{
final var lockPath = readMutex.getLockPath();
if (lockPath != null) {
return lockPath;
}
return writeMutex.getLockPath();
}
```
https://issues.apache.org/jira/browse/CURATOR-607

CURATOR-607: InterProcessReadWriteLock should expose exposing getLockPath

---

curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/ModeledFrameworkImpl.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestModeledFramework.java

Aside from the description, which captures the major issue:
- The ```fixAclList()``` change is unrelated, but jumped out as a build warning in my environment.
- There were no existing tests that exercised this class, so I didn't have any obvious place to hang a new unit test. Am I missing something obvious?

CURATOR-606: ModeledFrameworkImpl.update(T model, int version): Use version in all cases.

---

curator-framework/src/main/java/org/apache/curator/framework/state/ConnectionStateManager.java
curator-framework/src/test/java/org/apache/curator/framework/state/TestConnectionStateManager.java

If there is a problem posting the Expired KeeperState
during a session expiration, then the ZooKeeper event
thread will die without ever posting the Expired event.
This would then cause curator to keep trying to expire
the connection but it does nothing because the connection
is dead and no events will ever be posted.
This can be prevented by forcibly resetting the connection
if it's detected that the previous expiry had no effect
https://issues.apache.org/jira/browse/CURATOR-561
Same as #399, but from a different fork

[CURATOR-561] Reset connection after repeat expiry

---

curator-framework/src/test/java/org/apache/curator/framework/state/TestConnectionStateManager.java

Signed-off-by: tison <wander4096@gmail.com>
co https://github.com/apache/curator/pull/409/files#r815376664

CURATOR-633: Run TestConnectionStateManager tests in exact groups

---

pom.xml

When running `mvn clean install -DskipTests` on my Mac i get:
`Failed to execute goal org.commonjava.maven.plugins:directory-maven-plugin:0.1:highest-basedir (directories) on project apache-curator: Cannot find a single highest directory for this project set. First two candidates directories don't share a common root. -> [Help 1]`
Upgrading the plugin, I'm able to compile

CURATOR-625 Bump directory maven plugin version to 1.0

---

curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceProviderBuilder.java

1. Use internal consistently since PathChildrenCache uses internal.
2. Fix a typo.

Fix comment

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentTtlNode.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/nodes/TestPersistentTtlNode.java

The PR makes the `PersistentTtlNode` able to configure the PersistentNode's `useParentCreation` boolean flag introduced in https://github.com/apache/curator/pull/380.
By default, the flag is set to `true`.
https://issues.apache.org/jira/browse/CURATOR-643

CURATOR-643: Add option to disable parent creation for PersistentTtlNode

---

curator-test/src/main/java/org/apache/curator/test/DirectoryUtils.java
curator-test/src/main/java/org/apache/curator/test/InstanceSpec.java
pom.xml

CURATOR-642 Upgrades Guava from 27.0.1 to 31.1 and replaces usage of Guava `Files.createTempDir()` with Java NIO `Files.createTempDirectory()`

CURATOR-642 Upgrade Guava from 27.0.1 to 31.1

---

curator-client/pom.xml
curator-client/src/test/java/org/apache/curator/TestIs37.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReadOnly.java
curator-test-zk36/pom.xml
curator-test-zk36/src/test/java/org/apache/curator/zk36/TestIs36.java
curator-test-zk36/src/test/resources/log4j.properties
curator-test/src/main/java/org/apache/curator/test/QuorumConfigBuilder.java
pom.xml

`TestReadOnly` fails due to ZOOKEEPER-3863(apache/zookeeper#1380).
ZOOKEEPER-3863 uses `QuorumPeerConfig.localSessionsEnabled` to toggle
local sessions supports in `ReadOnlyZooKeeperServer`.
This pr populates `QuorumPeerConfig.localSessionsEnabled` and
`QuorumPeerConfig.localSessionsUpgradingEnabled` from system property
`readonlymode.enabled` for simplicity.

CURATOR-596: Upgrade ZooKeeper to 3.7.1

---

curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java

In Kubernetes, IP addresses are not resistant to pod restart. `InetSocketAddress.getAddress().getHostAddress()` could target to non ZooKeeper pods and causes curator fail to reach ZooKeeper ensemble.
Further more, this is compatible with `QuorumVerifier.toString` and `QuorumServer.toString`.

CURATOR-638: Use getHostString() to build connection string in EnsembleTracker

---

curator-framework/src/main/java/org/apache/curator/framework/CuratorFramework.java

Addresses https://issues.apache.org/jira/browse/CURATOR-648 
In my opinion the most likely resolution for this case is simply to fix the documentation, the changes in this PR do just that.

CURATOR-648: Fixed CuratorFramework#blockUntilConnected documentation

---

curator-client/src/main/java/org/apache/curator/utils/Compatibility.java

To be aligned with contract of `java.net.InetSocketAddress` it should take into account that `java.net.InetSocketAddress#getAddress` could return `null` which will mean unresolved address

CURATOR-538: address from InetSocketAddress could be null as it means unresolved address

---

curator-framework/pom.xml
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReadOnly.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/ChaosMonkeyCnxnFactory.java
curator-test/src/main/java/org/apache/curator/test/QuorumConfigBuilder.java
curator-test/src/main/java/org/apache/curator/test/TestingQuorumPeerMain.java
curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperMain.java
curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperServer.java
curator-test/src/main/java/org/apache/curator/test/ZooKeeperMainFace.java
curator-test/src/main/java/org/apache/curator/test/ZooKeeperServerEmbeddedAdapter.java
curator-test/src/test/java/org/apache/curator/test/TestTestingServer.java

This closes https://github.com/apache/curator/pull/379.

CURATOR-587. Use ZooKeeperServerEmbedded to start TestingServer

---

curator-recipes/pom.xml
curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/TestLeaderLatch.java
curator-test-zk35/pom.xml

See also:
* https://issues.apache.org/jira/browse/CURATOR-644
* https://issues.apache.org/jira/browse/CURATOR-645
Here we have two race conditions to cause livelock:
Case 1. Suppose there are two participants, p0 and p1:
T0. p1 is going to watch on preceding node belongs to p0.
T1. p0 gets reconnected, and thus reset its node, and create a new node to prepare watch on p1's node.
T2. p1 find preceding node has gone, and reset itself.
At the moment, p0 and p1 can be in the livelock that never see each other's node and infinitely reset themselves. This is the case reported by CURATOR-645.
Case 2. The similar case can happen even if there is only one participant:
~~If we still call `reset` when preceding node deleted by latter set new node, it's a live lock.~~
I cannot find a live lock here. …

CURATOR-644. CURATOR-645. Fix livelock in LeaderLatch

---

curator-test/src/main/java/org/apache/curator/test/InstanceSpec.java
curator-test/src/main/java/org/apache/curator/test/QuorumConfigBuilder.java
curator-test/src/main/java/org/apache/curator/test/QuorumPeerConfigBuilder.java
curator-test/src/main/java/org/apache/curator/test/TestingQuorumPeerMain.java
curator-test/src/main/java/org/apache/curator/test/TestingServer.java
curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperMain.java
curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperServer.java
curator-test/src/main/java/org/apache/curator/test/ZooKeeperMainFace.java
curator-test/src/main/java/org/apache/curator/test/ZooKeeperServerEmbeddedAdapter.java
curator-test/src/test/java/org/apache/curator/test/TestTestingServer.java

This commit tries to solve port conflict for `TestingServer` if port is unspecified(aka. `port <= 0`):
* Set `InstanceSpec.port` to 0 if port is unspecified.
* Save OS chosen bind port after started to maintain same port across restart.
Ideally, it should be possible to bootstrap `TestingCluster`(with unspecified ports) too with help from `reconfig`. But there are difficulties since election port, quorum port were not designed to be bound to `0` in ZooKeeper. `TestingServer` should be enough for most cases.
Users should resort to other solutions(eg. container) if they got bored by port conflict due to usages of `TestingCluster` and `TestingServer.restart`.

CURATOR-535: Fix client port conflict due to untrustworthy random port allocation

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessReadWriteLock.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestInterProcessReadWriteLock.java

With protected `getLockPath`, clients have to inherit them to use `getLockPath`, it is cumbersome and nonsense.

CURATOR-662: Export getLockPath for locks from InterProcessReadWriteLock

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelector.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelectorListener.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/TestLeaderSelector.java

Currently, `LeaderSelector.interruptLeadership` clould cancel queued election task before its execution which will break election loop.

CURATOR-518: Fix LeaderSelector requeue broken by interruptLeadership

---

curator-client/src/main/java/org/apache/curator/utils/Compatibility.java
curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java

This is an additional fix for [CURATOR-638](https://issues.apache.org/jira/browse/CURATOR-638) based on PR #425.

CURATOR-664: Use getHostString() to build connection string in EnsembleTracker even for wildcard addresses

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java

To ensure clarity and consistency, this PR replaces "JMV" with "JVM" in the LeaderLatch.java file.

Fix type "JMV" to "JVM" in LeaderLatch

---

curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorEventImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFramework.java

Previously, `unfixForNamespace` was called twice in background create. This will accidentally unfix node path if it happens to contain namespace in its prefix. Say, creating "/zoo/a" in namespace "/zoo" will get path "/a".

CURATOR-666: Fix twice unfixForNamespace in background create

---

.github/workflows/ci.yml
.gitignore
.mvn/extensions.xml
.mvn/ge-extensions.xml
.mvn/gradle-enterprise-custom-user-data.groovy
.mvn/gradle-enterprise.xml

https://issues.apache.org/jira/browse/CURATOR-669
See -
* https://github.com/apache/pulsar/pull/19133
* https://github.com/apache/pulsar/pull/19194
* https://the-asf.slack.com/archives/CBX4TSBQ8/p1672826514725099
I'd prefer to use this method for analyzing our flaky tests and time-consuming tests for further improving.

CURATOR-669. Integrate with ge.apache.org Gradle Enterprise server

---

curator-framework/src/main/java/org/apache/curator/framework/imps/EnsembleTracker.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java

Curator uses `EnsembleProvider::getConnectionString` as connection string to `ZooKeeper`. `EnsembleTracker` subscribes to config node to construct up to date connection string for `EnsembleProvider`. This is great.
But, currently, `EnsembleTracker` omits chroot part of connection string which could cause curator locating at ZooKeeper root after reconnection. This could damage clients' data hierarchy in unexpected manner.

CURATOR-593: Append chroot for EnsembleProvider::setConnectionString in EnsembleTracker

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/LockInternals.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestLockInternals.java
curator-test/src/main/java/org/apache/curator/test/BaseClassForTests.java

Suppress exception from `deleteOurPath` if we are throwing.

CURATOR-41: Suppress secondary exception in LockInternals.attemptLock

---

curator-framework/src/main/java/org/apache/curator/framework/api/ErrorListenerEnsembleable.java
curator-framework/src/main/java/org/apache/curator/framework/api/ErrorListenerMultiTransactionMain.java
curator-framework/src/main/java/org/apache/curator/framework/api/ErrorListenerPathAndBytesable.java
curator-framework/src/main/java/org/apache/curator/framework/api/ErrorListenerPathable.java
curator-framework/src/main/java/org/apache/curator/framework/api/ErrorListenerReconfigBuilderMain.java
curator-test/src/main/java/org/apache/curator/test/compatibility/Timing2.java
curator-x-async/src/main/java/org/apache/curator/x/async/details/BuilderCommon.java
curator-x-async/src/test/java/org/apache/curator/framework/imps/TestFrameworkBackground.java
curator-x-async/src/test/java/org/apache/curator/x/async/CompletableBaseClassForTests.java

`AsyncCuratorFramework` binds its `UnhandledErrorListener` to operation level which could prevent `AsyncStage` from completion if exception is swallowed by that listener.
In any cases, a framework level error listener should not prevent an operation future from completion.

CURATOR-675: Fix AsyncCuratorFramework's UnhandledErrorListener hang AsyncStage

---

pom.xml

https://issues.apache.org/jira/browse/CURATOR-683
Resolves CVEs:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42004 (resource exhaustion)
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42003 (resource exhaustion)
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-46877 (denial of service)
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518 (denial of service)
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25649 (data integrity)

CURATOR-683: com.fasterxml.jackson.core version 2.13.5

---

curator-framework/src/main/java/org/apache/curator/framework/imps/GetConfigBuilderImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFramework.java

`getConfig` will read data from path "/zookeeper/config" which belongs to no namespace nor chroot in ZooKeeper side. Path in background event or watch event should stick to "/zookeeper/config".
See also:
* https://issues.apache.org/jira/browse/ZOOKEEPER-4601
* https://lists.apache.org/thread/2tsg1hcopl80zot12tqrynrbg2h792jf

CURATOR-667: Fix abnormal event config path from getConfig

---

curator-framework/pom.xml
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/NamespaceFacadeCache.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFramework.java
curator-test-zk35/pom.xml
curator-test-zk36/pom.xml
pom.xml

In construction of `CuratorFrameworkImpl`, it constructs a sub class `NamespaceFacade` for commonly used `nullNamespace`. Due to this recursive construction, `nullNamespace` has uninitialized fields which cause NPT in certain cases.
This commit solves this by postponing `nullNamespace` creation.

CURATOR-626: Postpone null namespace facade creation to avoid partial initialization

---

curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestInterProcessMutexBase.java

Placing `Thread.sleep(550)` after `mutex.release()` and before `hasLock.set(false)` will fail this test more frequently.

CURATOR-681: Fix flaky TestInterProcessMutex.testReentrantSingleLock

---

curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/DeleteBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/ExistsBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/OperationAndData.java
curator-framework/src/main/java/org/apache/curator/framework/imps/SetDataBuilderImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestFramework.java

Currently, some background operations use auxiliary sub operations to
complete task in case of primary conditions are not satisfied. But most
of these sub operations count only success path, so they will hang
`BackgroundCallback` if they are failed or cancelled due to framework
closed.
This is the leftover of [CURATOR-673][](https://github.com/apache/curator/pull/464).
[CURATOR-673]: https://issues.apache.org/jira/browse/CURATOR-673

CURATOR-677: Complete BackgroundCallback if sub operation failed or cancelled

---

pom.xml

Ref - CURATOR-693
The PR is aiming to bump zk to 3.7.2 to address CVE-2023-44981

CURATOR-693. Bump zookeeper to 3.7.2

---

curator-client/src/main/java/org/apache/curator/retry/ExponentialBackoffRetry.java

fix sleepMs overflow
```java
public class Main {
private static final Random random = new Random();
private static int baseSleepTimeMs = Integer.MAX_VALUE;
public static void main(String[] args) {
int retryCount = 2;
long sleepMs1 = baseSleepTimeMs * Math.min(2, random.nextInt(1 << (retryCount + 1)));
long sleepMs2 = (long) baseSleepTimeMs * Math.min(2, random.nextInt(1 << (retryCount + 1)));
System.out.println(sleepMs1);
System.out.println(sleepMs2);
}
}
```

CURATOR-262. Fix sleepMs overflow

---

curator-client/src/main/java/org/apache/curator/utils/Compatibility.java
curator-client/src/main/java/org/apache/curator/utils/ZookeeperCompatibility.java
curator-framework/src/main/java/org/apache/curator/framework/CuratorFramework.java
curator-framework/src/main/java/org/apache/curator/framework/CuratorFrameworkFactory.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheBridgeBuilderImpl.java
curator-test-zk35/src/test/java/org/apache/curator/zk35/TestIs35.java
curator-test-zk36/src/test/java/org/apache/curator/zk36/TestIs36.java
curator-x-async/src/main/java/org/apache/curator/x/async/details/AsyncCuratorFrameworkImpl.java

Add new interface ZookeeperCompatibility to represent server compatibility in addition to the existing Compatibility class (which represents client compatibility).
Enhance CuratorFramework to accept ZookeeperCompatibility instance, allowing user to specify which server version to target (default is LATEST).

CURATOR-704. Add server compatibility check support

---

curator-recipes/pom.xml
curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/leader/TestLeaderLatch.java

A possible fix to CURATOR-696.
* Refer to https://github.com/apache/druid/issues/16411.
* Refer to #430.
I'm thinking whether this has more corner cases ...
cc @gianm @kezhuw @eolivelli

CURATOR-696. Fix double leader for LeaderLatch

---

.github/workflows/ci.yml

This reduces our ci time from 140 mins to 40 mins.

CURATOR-706: Parallelize zk compatibility tests and unit tests

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/IllegalTrySetVersionException.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedCount.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedValue.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/VersionedValue.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/shared/TestSharedCount.java

I met one issue which will never update znode value successfully when integer overflow (-2147483648) of znode data version using curator to invoke SharedCount#trySetCount(VersionedValue<Integer>, int).
After dig the limitation logic and found that here could be the root cause.
https://github.com/apache/curator/blob/master/curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedValue.java#L196-L209
My environment is, curator version: 2.10.0, zookeeper version: 3.4.6
Ref - CURATOR-688

CURATOR-688. SharedCount will be never updated successful when version of ZNode is overflow.

---

curator-framework/src/test/java/org/apache/curator/framework/imps/TestCreate.java

CURATOR-221 reported that namespace paths are created with no ACL. Though, I belive that it should be fixed by CURATOR-222. It should still be a good to write tests to assert that.

CURATOR-714: Assert that namespace paths are created using CuratorFramework's ACLProvider

---

curator-client/src/main/java/org/apache/curator/utils/ZKPaths.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestCreate.java
pom.xml

This PR tackles the problem reported in https://issues.apache.org/jira/browse/CURATOR-715.
Namely, that ZooKeeper trees where upper nodes have restricted READ ACLs, it is not possible to use `creatingParentsIfNeeded` without changing the ACLs. 
This is because the implementation prior to this patch iterated from root node to the newly created one, checking existence of all intermediate nodes.
This patch changes that approach from top-down to bottom-up and the first ancestor that exists is where the validation stops thus avoiding `exists` checks on the higher nodes with more restricted access.
This is only relevant since https://issues.apache.org/jira/browse/ZOOKEEPER-2590

CURATOR-715/mkdirs/bottom up existence check

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCache.java

There is a typo in the CuratorCache Javadoc:
> **Image** another client that isn't partitioned, deletes "/foo/bar" and then a third client re-creates "/foo/bar"
"Image" should be "Imagine".

CURATOR-717: Fix typo in CuratorCache Javadoc

---

curator-client/src/main/java/org/apache/curator/CuratorZookeeperClient.java

https://issues.apache.org/jira/browse/CURATOR-720
Stop a retry loop if the client is stopped.

CURATOR-720: Stop retry if client is closed

---

curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestCreate.java

https://issues.apache.org/jira/browse/CURATOR-719
This fix really just lets the `catch (KeeperException.NodeExistsException e)` clause catch exceptions thrown in the `if (createParentsIfNeeded)` clause. Previously, since the two `catch` statements were for the same try, the `KeeperException.NodeExistsException` logic would not be called if that error was thrown when creating the node after creating the parents. This case can easily be seen when trying to call create.orSetData() in parallel on the same node, while creating parents if needed. This is because the `NoNodeException` would be thrown for both parallel calls, but only one would be able to create the new node in the catch statement, and the other would get an un-catchable `NodeExistsException`.

CURATOR-719: Fix orSetData for parallel create calls

---

curator-client/src/main/java/org/apache/curator/drivers/OperationTrace.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorEventImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorMultiTransactionImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/GetChildrenBuilderImpl.java

https://issues.apache.org/jira/browse/CURATOR-726
In Apache Solr, we are trying to refactor all of our custom ZK interaction logic to use Curator. One of the things we do is implement metrics on our interactions with ZK. Curator allows us to do this with Tracing and CuratorListeners. However there are two things that don't give us the information we need.
1. The "Get Children" command trace does not give the information needed for the number of Children fetched.
2. The "Multi Transaction" command trace:
- The trace does not give the number of commands that are in the transaction, which is something we track currently.
- The MultiTransaction trace is not an AdvancedTrace, it's a normal Trace for some reason. AdvancedTracerDrivers cannot read regular traces, so we can't even see these. We …

CURATOR-726: Improve tracing for certain operations

---

.mvn/extensions.xml

I saw following logs in test phase of https://github.com/apache/curator/actions/runs/12448243386/job/34752620203.
```
[INFO] Publishing build scan...
[INFO] 
[INFO] The request was rejected.
Develocity Maven extension version 1.23 is newer than the newest version supported by Develocity 2024.2.2 which is 1.22. Please update to a newer version of Develocity.
```

hotfix: build scan rejected by ge.apache.org

---

.asf.yaml

Here we have several open issues:
1. @gmcdonald, will this move stop all the possibility that INFRA will help migrate JIRA tickets? I remember that I was told not to enable GitHub Issues by myself but to wait for INFRA's response. But as you can see, the ticket gets stalled, and we don't know whether it will make progress.
2. The PR title and commit message flavor may change. As we now follow `CURATOR-xxx` where `xxx` is mapped to a JIRA ticket and we have the autolink to JIRA. With GitHub issues, it can be easily linked within the PR description. And thus,
1. I'd keep the `autolink_jira` option for all existing PRs and commits;
2. I'd suggest all the following PR/commit use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
3. The release note generation step in …

chore: Enable GitHub Issues

---

curator-client/src/main/java/org/apache/curator/utils/ZKPaths.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestCreate.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestEnsureContainers.java
curator-test-zk37/pom.xml
curator-test-zk38/pom.xml

`ZkPaths::mkdir("/bar/foo")` will not run into `NoAuthException` if
"/bar/foo" exists, and we have `READ` permission to "/bar/foo" but not
`CREATE` permission to "/bar".

CURATOR-728: Not issue ZooKeeper::create if possible in ZkPaths::mkdirs

---

pom.xml

This removes duplicate class ListenableFuture.
See more at https://github.com/google/guava/issues/7385

[CURATOR-721] Upgrade Guava Listenablefuture

---

.github/workflows/ci.yml
.mvn/develocity.xml
.mvn/extensions.xml

This PR migrates the Curator project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
Additionally, this PR sets a projectId for use by Develocity.
https://issues.apache.org/jira/browse/CURATOR-730

[CURATOR-730] Publish build scans to develocity.apache.org

---

curator-framework/src/main/java/org/apache/curator/framework/api/CuratorClosedException.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/watch/PersistentWatcher.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/watch/TestPersistentWatcher.java

The dead loop is multifold:
1. `CuratorFramework::watchers` does not check `CuratorFrameworkState` as `getData` or others do.
2. `PersistentWatcher` loops itself through `reset` in `BackgroundCallback`.
3. Callback in `inBackground(callback).forPath(path)` is invoked synchronously.
This commit enforces `CuratorFrameworkState` checking also to `watchers`, `watches`, `sync`, `reconfig` and `getConfig`.
Additionally, this commit will issue `KeeperState.Closed` to listeners of `PersistentWatcher` when curator get closed. This is not required to fix CURATOR-729, but will make the closing behavior consistent with ZooKeeper. Also, I think it is good for asynchronous `Watcher`.
Refs: CURATOR-529, CURATOR-673

CURATOR-729: Fix PersistentWatcher dead loop after curator closed

---

curator-framework/src/main/java/org/apache/curator/framework/CuratorFramework.java
curator-framework/src/main/java/org/apache/curator/framework/CuratorFrameworkFactory.java
curator-framework/src/main/java/org/apache/curator/framework/api/Compressible.java
curator-framework/src/main/java/org/apache/curator/framework/api/Decompressible.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/GetDataBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/SetDataBuilderImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/TempGetDataBuilderImpl.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestCompression.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestCompressionInTransactionNew.java
curator-framework/src/test/java/org/apache/curator/framework/imps/TestCompressionInTransactionOld.java
curator-x-async/src/main/java/org/apache/curator/x/async/api/AsyncGetDataBuilder.java
curator-x-async/src/main/java/org/apache/curator/x/async/api/AsyncSetDataBuilder.java
curator-x-async/src/main/java/org/apache/curator/x/async/api/AsyncTransactionCreateBuilder.java
curator-x-async/src/main/java/org/apache/curator/x/async/api/AsyncTransactionSetDataBuilder.java
curator-x-async/src/main/java/org/apache/curator/x/async/api/CreateOption.java
curator-x-async/src/main/java/org/apache/curator/x/async/details/AsyncCreateBuilderImpl.java
curator-x-async/src/main/java/org/apache/curator/x/async/details/AsyncGetDataBuilderImpl.java
curator-x-async/src/main/java/org/apache/curator/x/async/details/AsyncSetDataBuilderImpl.java
curator-x-async/src/main/java/org/apache/curator/x/async/details/AsyncTransactionOpImpl.java
curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/ModeledFrameworkImpl.java
curator-x-async/src/test/java/org/apache/curator/x/async/TestBasicOperations.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestModeledFramework.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestModeledFrameworkBase.java

https://issues.apache.org/jira/browse/CURATOR-725
Allow users to use a CuratorFramework setting to enable compression on all create/setData/getData requests. When using this flag with a custom `CompressionProvider`, this can easily allow for a filtered compression implementation.

CURATOR-725: Allow for global compression

---

curator-framework/src/main/java/org/apache/curator/framework/state/ConnectionStateManager.java

Fix bug of useSessionTimeoutMs overflow. 
This closes https://github.com/apache/curator/issues/1248.

GH-1248. Fix bug of useSessionTimeoutMs overflow

---

curator-client/src/main/java/org/apache/curator/CuratorZookeeperClient.java
curator-client/src/main/java/org/apache/curator/retry/ExponentialBackoffRetry.java
curator-examples/src/main/java/cache/CuratorCacheExample.java
curator-examples/src/main/java/pubsub/SubPubTest.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkBase.java
curator-framework/src/main/java/org/apache/curator/framework/listen/MappingListenerManager.java
curator-framework/src/main/java/org/apache/curator/framework/state/ConnectionStateManager.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/atomic/DistributedAtomicValue.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/barriers/DistributedDoubleBarrier.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCache.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/queue/QueueSharder.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/watch/PersistentWatcher.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestEventOrdering.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestTreeCacheRandomTree.java
curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperMain.java
curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/rest/DiscoveryResource.java
curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/rest/InstanceCleanup.java

This closes https://github.com/apache/curator/issues/1072
cc @kezhuw @eolivelli

chore: fixup logging and other style issues

---

curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/CachedModeledFrameworkImpl.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestCachedModeledFramework.java

This is an alternative, simpler implementation to https://github.com/apache/curator/pull/1247 with the same motivation, namely to solve https://github.com/apache/curator/issues/1246

GH-1246. Asynchronously initialize cache before reading II

---

curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/CachedModeledFrameworkImpl.java
curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/ModeledCacheImpl.java
curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestCachedModeledFramework.java

Fix `CachedModeledFramework::list` so it returns unfiltered list of children based on the cache path (not client path). See https://github.com/apache/curator/issues/1256 for more details.
Also added really minor fix to `CachedModeledFramework::readThrough(Stat)`. This surfaced after I enhanced the tests a bit. This bug predates https://github.com/apache/curator/pull/1250

GH 1256. Fix cached modeled framework list

---

curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedCount.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/shared/SharedValue.java

Document read effects after SharedValue.setValue

---

curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkBase.java
curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
curator-framework/src/main/java/org/apache/curator/framework/imps/DelegatingCuratorFramework.java
curator-recipes/src/main/java/org/apache/curator/framework/recipes/watch/PersistentWatcher.java
curator-recipes/src/test/java/org/apache/curator/framework/recipes/watch/TestPersistentWatcher.java

`NamespaceFacade` does not support `getCuratorListenable` while #520 use it to listen for `CuratorEventType.CLOSING` to fix CURATOR-729.
This commit exports `CuratorFrameworkBase::client` to retrieve underlying framework client to listen for for `CuratorEventType.CLOSING`.
Fixes #1259.

Fix PersistentWatcher not working with NamespaceFacade

---

pom.xml

This closes https://github.com/apache/curator/issues/1269.

GH-1269: Bump Jetty to 9.4.57.v20241219

---

pom.xml

This closes https://github.com/apache/curator/issues/1266.

GH-1266. Bump jackson-core from 2.13.5 to 2.18.1

---

curator-framework/src/test/java/org/apache/curator/framework/imps/TestReconfiguration.java

`testAdd`, `testAddAsync` and `testAddAndRemove` asserts that
`EnsembleProvider::setConnectionString` is updated with new connect
string after ensemble changed. Since the update is asynchronous, so they
should wait before assertion.

Fix flaky tests in TestReconfiguration

---

curator-test/src/main/java/org/apache/curator/test/Timing.java

ZOOKEEPER-4508 reports `SessionExpired` after exhausting session timeout
in session establishment instead of endless retries. It is easy to get
in this now with small session timeout.
Besides above, `sessionTimeoutMs` should bigger than `connectionTimeoutMs`,
while default `Timing::session()` and `Timing::connection()` are `2s` and
`10s` respectively now.
```
// from CuratorZookeeperClient
if (sessionTimeoutMs < connectionTimeoutMs) {
log.warn(
"session timeout [{}] is less than connection timeout [{}]", sessionTimeoutMs, connectionTimeoutMs);
}
```

Fix flaky TestReadOnly.testConnectionStateNewClient in ZooKeeper 3.9.3

---

curator-test/src/main/java/org/apache/curator/test/InstanceSpec.java
curator-test/src/main/java/org/apache/curator/test/InstanceSpecBuilder.java
curator-test/src/main/java/org/apache/curator/test/TestingServer.java
curator-test/src/test/java/org/apache/curator/test/TestQuorumConfigBuilder.java
curator-test/src/test/java/org/apache/curator/test/TestTestingServer.java

It is hard for us to know what does `new InstanceSpec(null, -1, -1, -1, true, -1, -1, -1)` means now.
Closes #1222.

Add builder to construct InstanceSpec
