apache/curator

- curator-x-discovery/src/main/java/org/apache/curator/x/discovery/ServiceDiscoveryBuilder.java
- curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceDiscoveryImpl.java
- curator-x-discovery/src/test/java/org/apache/curator/x/discovery/TestServiceDiscovery.java
- curator-x-discovery/src/test/java/org/apache/curator/x/discovery/details/TestWatchedInstances.java
Added a way to watch registered services so that tools such as admin consoles can change values and have SD recognize the changes
> Curator 176

- curator-framework/src/main/java/org/apache/curator/framework/AuthInfo.java
- curator-framework/src/main/java/org/apache/curator/framework/CuratorFrameworkFactory.java
- curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
- curator-framework/src/test/java/org/apache/curator/framework/imps/TestFramework.java
I was able to run the test through IntelliJ, but had trouble building and testing on command line.
> CURATOR-111: Add authorization(List<AuthInfo)

- curator-framework/src/main/java/org/apache/curator/framework/CuratorFrameworkFactory.java
- curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorFrameworkImpl.java
- curator-framework/src/test/java/org/apache/curator/framework/imps/TestFramework.java
auth data is stored in a single list. Modified tests to have both a single
auth and multiple auth case.
> CURATOR-111 - Modified the authorization handling so that the underlying

- pom.xml
Update parent pom to apache 16 and remove duplicative version declarations. Let apache handle it where we don't conflict.
> CURATOR-204 Update parent pom to apache:16

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/queue/DistributedQueue.java
- curator-recipes/src/test/java/org/apache/curator/framework/recipes/queue/TestDistributedIdQueue.java
Made the one-line fix in DistributedQueue.java and added a test-case in TestDistributedIdQueue.java.
> Curator-224: Fixed the requeuing problem with DistributedIdQueue.

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentEphemeralNode.java
- curator-recipes/src/test/java/org/apache/curator/framework/recipes/nodes/TestPersistentEphemeralNode.java
See https://issues.apache.org/jira/browse/CURATOR-258
> [CURATOR-258] PersistentEphemeralNode stops watching after first WatchedEvent

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCache.java
- curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCacheEvent.java
- curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestTreeCache.java
@Randgalt @madrob @cammckenzie
> TreeCache should inform listeners when its fully reconnected.

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/TreeCache.java
Debug logging I found useful for debugging the killedSession() problem.
@Randgalt
> TreeCache debug logging

- curator-framework/src/main/java/org/apache/curator/framework/imps/NamespaceWatcher.java
- curator-framework/src/test/java/org/apache/curator/framework/imps/TestWatcherIdentity.java
> NamespaceWatcher should only equals other NamespaceWatcher

- curator-client/src/main/java/org/apache/curator/retry/BoundedExponentialBackoffRetry.java
- curator-client/src/main/java/org/apache/curator/retry/ExponentialBackoffRetry.java
- curator-client/src/main/java/org/apache/curator/retry/RetryNTimes.java
- curator-client/src/main/java/org/apache/curator/retry/RetryUntilElapsed.java
- curator-client/src/main/java/org/apache/curator/retry/SleepingRetry.java
https://issues.apache.org/jira/browse/CURATOR-262
> CURATOR-262: Fixed integer overflow issue with sleepMs

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/locks/InterProcessSemaphoreV2.java
- curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestInterProcessSemaphore.java
If there is a network event after the semaphore's node is created but before getChildren() is called, the previous implementation would orphan the newly created node causing a deadlock later on
> [CURATOR-335] InterProcessSemaphoreV2 can deadlock under network stress

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelector.java
Do not attempt to release a mutex unless it has actually been acquired
> CURATOR-337: Do not attempt to release a mutex unless it has actually been acquired

- curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
- curator-framework/src/test/java/org/apache/curator/framework/imps/TestFramework.java
Resulted in infinite amount of retries
https://issues.apache.org/jira/browse/CURATOR-341
> CURATOR-341: Don't retry create operation after setData

- curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
- curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorMultiTransactionImpl.java
- curator-framework/src/main/java/org/apache/curator/framework/schema/Schema.java
validateCreate() should be taking a path argument. The class field "path" was hiding this so I renamed that as well.
> [CURATOR-348] validateCreate() should be taking a path argument

- curator-framework/src/main/java/org/apache/curator/framework/imps/CuratorMultiTransactionImpl.java
- curator-framework/src/main/java/org/apache/curator/framework/imps/DeleteBuilderImpl.java
- curator-framework/src/main/java/org/apache/curator/framework/imps/ExistsBuilderImpl.java
- curator-framework/src/main/java/org/apache/curator/framework/imps/GetChildrenBuilderImpl.java
- curator-framework/src/main/java/org/apache/curator/framework/imps/GetDataBuilderImpl.java
- curator-framework/src/main/java/org/apache/curator/framework/schema/Schema.java
- curator-framework/src/main/java/org/apache/curator/framework/schema/SchemaSet.java
- curator-framework/src/main/java/org/apache/curator/framework/schema/SchemaViolation.java
Better exceptions messaging when there is a Schema violation. This is much more useful for debugging purposes
> [CURATOR-352] SchemaViolation errors do not contain enough information

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelector.java
-If leadership changes between the getParticipantNodes() call and the getLeader() internal call the NoNodeException is now handled and the next child in the list is evaluated.
Another option would be to just return the default empty Participant object and not iterate over the whole list of participants.
> CURATOR-358 - Fixed race condition with getLeader()

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/nodes/PersistentNode.java
localCreateMethod could be null in a race condition
> [CURATOR-395] Potential null dereference in PersistentNode

- curator-x-async/src/main/java/org/apache/curator/x/async/AsyncWrappers.java
- curator-x-async/src/main/java/org/apache/curator/x/async/modeled/ModeledFrameworkBuilder.java
- curator-x-async/src/main/java/org/apache/curator/x/async/modeled/ModeledOptions.java
- curator-x-async/src/main/java/org/apache/curator/x/async/modeled/details/ModeledFrameworkImpl.java
1. AsyncWrappers.asyncEnsureContainers was just wrong - this is a better implementation
2. Added raw serializer constant
3. Add ModeledOptions which can be expanded in the future. For now it just has ignoreMissingNodesForChildren
> A few things for CURATOR-397

- src/site/confluence/zk-compatibility.confluence
Update docs to document how to use the curator-test module with ZooKeeper 3.4.x
> [CURATOR-446] Update docs to document how to use the curator-test module with ZooKeeper 3.4.x

- curator-x-async/pom.xml
- pom.xml
- src/site/site.xml
Move to ZooKeeper 3.5.4-beta and Java 8
> [CURATOR-471] Move to Java 8

- curator-framework/src/test/java/org/apache/curator/framework/imps/TestCleanState.java
- curator-framework/src/test/java/org/apache/curator/framework/imps/TestFramework.java
- curator-framework/src/test/java/org/apache/curator/framework/imps/TestFrameworkEdges.java
- curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestNodeCache.java
- curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestPathChildrenCache.java
- curator-recipes/src/test/java/org/apache/curator/framework/recipes/locks/TestInterProcessSemaphoreMutex.java
- curator-test-zk34/pom.xml
- curator-test/src/main/java/org/apache/curator/test/BaseClassForTests.java
Some of the tests are flakey and fail intermittently. This task will remain open as a container for fixing tests.
> [CURATOR-490] Make the tests more resilient

- doap.rdf
- pom.xml
1. fix mailing-lists.html buttons to have mailto prefix
2. fix doap.rdf to refer correctly to mailing-lists.html
> fix mailing list issues

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/barriers/DistributedDoubleBarrier.java
> [CURATOR-536] break infinite loop in internalLeave() on timeout

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/NodeCache.java
> [CURATOR-556] Fix typo

- curator-recipes/src/test/java/org/apache/curator/connection/TestThreadLocalRetryLoop.java
test used InterProcessReadWriteLock - the problem is that the retry can end up in background loop which has its own thread thereby spoiling the test. Instead use a foreground operation for consistent tests
> [CURATOR-559] testThreadedRecursingRetry

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheListenerBuilder.java
- curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheListenerBuilderImpl.java
- curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/PathChildrenCacheListenerWrapper.java
- curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestCuratorCacheWrappers.java
- curator-x-discovery/src/main/java/org/apache/curator/x/discovery/details/ServiceCacheImpl.java
see https://issues.apache.org/jira/browse/CURATOR-574
> CURATOR-574 DiscoveryService fatal error on deserializing an empty byte[] as JSON

- pom.xml
cc @Randgalt @eolivelli I can see some of our commits merge without merge commits while others with. Thus I'm not sure what it the method I should put this commit onto master branch. Open a pull request for your advice.
> Add tison as Committer and PMC

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelector.java
> Fix typo in LeaderSelector.java

- curator-framework/src/main/java/org/apache/curator/framework/schema/Schema.java
Fix one bug. See http://errorprone.info
> CURATOR-458: Fix a bug spotted by error-prone compiler

- curator-client/pom.xml
- curator-examples/pom.xml
- curator-framework/pom.xml
- curator-recipes/pom.xml
- curator-test/pom.xml
- curator-x-discovery-server/pom.xml
- curator-x-discovery/pom.xml
- pom.xml
Keep `http://www.apache.org/licenses/LICENSE-2.0` as is.
> CURATOR-524. Fix all URLs as https

- NOTICE
- curator-client/NOTICE
- curator-examples/NOTICE
- curator-framework/NOTICE
- curator-recipes/NOTICE
- curator-test/NOTICE
- curator-x-discovery-server/NOTICE
- curator-x-discovery/NOTICE
Isolated part in https://github.com/apache/curator/pull/444
> [CURATOR-661] Update copyright year in NOTICE files

- curator-client/src/main/java/org/apache/curator/utils/ZKPaths.java
- curator-framework/src/main/java/org/apache/curator/framework/imps/CreateBuilderImpl.java
- curator-x-async/src/test/java/org/apache/curator/x/async/modeled/TestModeledFramework.java
See https://issues.apache.org/jira/browse/CURATOR-665 for details.
> CURATOR-665: Convey mkdirs exception to create backgorund

- .asf.yaml
- .github/workflows/ci.yml
Pending for rebase and merged.
cc @kezhuw @eolivelli
> Disable fail-fast to avoid heavy rerun 

- .github/workflows/ci.yml
- .mvn/wrapper/maven-wrapper.properties
- curator-client/src/test/java/org/apache/curator/TestEnsurePath.java
- curator-framework/src/main/java/org/apache/curator/framework/imps/GzipCompressionProvider.java
- curator-framework/src/test/java/org/apache/curator/framework/imps/TestGzipCompressionProvider.java
- curator-framework/src/test/java/org/apache/curator/framework/imps/TestWatcherIdentity.java
- curator-x-discovery-server/src/main/java/org/apache/curator/x/discovery/server/contexts/GenericDiscoveryContext.java
- mvnw
- mvnw.cmd
- pom.xml
https://issues.apache.org/jira/browse/CURATOR-672
Ref -
* https://github.com/apache/curator/pull/410
> CURATOR-672. Ensure JDK 17 support

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderSelector.java
`TestLeaderSelectorCluster.testLostRestart` depends on success `LeaderSelector::requeue` after observing `hasLeadership` and then `!hasLeadership`. #446(CURATOR-518) breaks this.
Instead of simply looping till success `LeaderSelector::requeue`, I tend to revert to old behavior as it was that since its introduce in eb4d2aaf7702e7e5ffbf1c1dd8544e88b1171045.
Though, we can't depend this in case of no leadership was ever granted. In this case, when session expired, I guess looping on `requeue` may be the only option. Anyway, `requeue` is somewhat hard to use correctly.
> CURATOR-671: Make sure success LeaderSelector::requeue after observing hasLeadership and then !hasLeadership

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/CuratorCacheImpl.java
- curator-recipes/src/main/java/org/apache/curator/framework/recipes/cache/OutstandingOps.java
- curator-recipes/src/test/java/org/apache/curator/framework/recipes/cache/TestCuratorCache.java
- curator-test/src/main/java/org/apache/curator/test/BaseClassForTests.java
This closes https://github.com/apache/curator/pull/479.
Ref - CURATOR-690
> CURATOR-690. CuratorCache fails to load the cache if there are more than 64k child znodes

- curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java
> CURATOR-521. Check LeaderLatch#close(CloseMode) does not accept null

- pom.xml
> CURATOR-697. Upgrade Apache Parent POM to 31
